//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelImage
    {
        public int ID { get; set; }
        public int HotelID { get; set; }
        public byte[] imageSourse { get; set; }
    
        public virtual Hotels Hotels { get; set; }
    }
}
